replicaCount: 1

image:
  repository: surajpatil7438/frontend-service
  tag: 1.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3002

resources: {}

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70